### ISSUE TITLE
On Pressing (ctrl & +) the ide "Save"  "Copy"  "New Code" converts to symbols

### ISSUE THREAD

**Issue by anjali1102** [coding-minutes/coding-minutes-ide#25]
On Pressing (ctrl & +) the ide "Save"  "Copy"  "New Code" converts to symbols

https://user-images.githubusercontent.com/56559378/138583435-1faefcd3-795e-4ec9-b977-1f1d9b113c34.mp4

**Comment by tarunluthra123** [comment]
Hey @anjali1102 
That is an intended feature. Basically when there is not enough screen space available, we change the options to display icons instead of their titles so as to save space and use it properly. 

Thanks for reaching out to us though. 

I'll be marking this issue as closed.
