### ISSUE TITLE
Output css on long output

### ISSUE THREAD

**Issue by dhwaj1902** [coding-minutes/coding-minutes-ide#9]
When there is a long output ``io-navigation`` get disturbed/go down because ``io-box`` height is not defined as shown below:

![image](https://user-images.githubusercontent.com/57860123/125818442-eedcac3e-84cd-42b8-a2d1-8daef92f335d.png)

#### How it can be improved?
We can define the height of the ``output-box``.

##### please assign me this issue, I want to work on it.

**Comment by jatinkatyal13** [comment]
That's a nice find @dhwaj1902, thanks for taking time and fixing this as well. Although in our newer deployment we've already fixed this and the tabination has gone away. 

Hoping to see more of your contributions soon 🚀

**Comment by dhwaj1902** [comment]
ok, Great😊
